# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "About Me"
  url = "#aboutme"
  weight = 20

[[main]]
  name = "Impact & Engagement"
  url = "#outreach"
  weight = 25

[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 30

[[main]]
   identifier = "Projects1"
   name = "Overview"
   url = "/projects/"
   parent = "Projects"
   weight = 1

[[main]]
   identifier = "Projects2"
   name = "Balancing Social Care Priorities"
   url = "/projects#balancing-social-care-priorities"
   parent = "Projects"
   weight = 2

[[main]]
   identifier = "Projects3"
   name = "Preferences for Differentiated Representation"
   url = "/projects#preferences-for-differentiated-representation"
   parent = "Projects"
   weight = 3

[[main]]
   identifier = "Projects4"
   name = "Universalism and the Welfare State"
   url = "/projects#universalism-and-the-welfare-state"
   parent = "Projects"
   weight = 4

[[main]]
   identifier = "Projects5"
   name = "Insiders and Outsiders"
   url = "/projects#insiders-and-outsiders"
   parent = "Projects"
   weight = 5

[[main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 40

[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
   name = "CV"
   url = "files/CV.pdf"
   weight = 60
